- hosts: all
- name: manage groups and users
  hosts: all
  become: yes
  tasks:
    - name: create devops and qa group
      group:
        name: "{{ item }}"
        state: present
      loop:
        - devops
        - qa

    - name: create users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        state: present
      loop:
      - { name: "aizat", groups: "devops" }
      - { name: "tim", groups: "qa" }
      - { name: "ann", groups: "qa" }
